#!/bin/bash
## Bash Script to clear cached memory on (Ubuntu/Debian) Linux
##	sudo sh /home/pi/programs/command/HArestart.sh
### BEGIN INIT INFO
# Provides:          HArestart.sh
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: update_hass.sh
### END INIT INFO

mkdir -p /home/pi/log/install
LOG_FILE="/home/pi/log/HArestart.log"

#systemctl stop home-assistant@homeassistant.service          | tee -a 	"$LOG_FILE"

#start command#

systemctl stop home-assistant@homeassistant.service          | tee -a 	"$LOG_FILE"
rm /home/homeassistant/.homeassistant/home-assistant.log     | tee -a 	"$LOG_FILE"
rm /home/homeassistant/.homeassistant/home-assistant_v2.db   | tee -a 	"$LOG_FILE"
systemctl restart home-assistant@homeassistant.service       | tee -a 	"$LOG_FILE"
sleep 10 
systemctl status home-assistant@homeassistant.service        | tee -a 	"$LOG_FILE"


exit 1
