#!/bin/bash
## Bash Script to clear cached memory on (Ubuntu/Debian) Linux
##	sudo sh /home/pi/programs/command/HAupdate.sh
### BEGIN INIT INFO
# Provides:          update_hass.sh
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: update_hass.sh
### END INIT INFO

mkdir -p /home/pi/log/install
LOG_FILE="/home/pi/log/HAupdate.log"


rm /home/homeassistant/.homeassistant/home-assistant.log     | tee -a 	"$LOG_FILE"
rm /home/homeassistant/.homeassistant/home-assistant_v2.db   | tee -a 	"$LOG_FILE"

systemctl stop home-assistant@homeassistant.service          | tee -a 	"$LOG_FILE"
su -s /bin/bash homeassistant                                | tee -a 	"$LOG_FILE"
echo "UPDATE STARTING....."                                  | tee -a 	"$LOG_FILE"
echo " "                                                     | tee -a 	"$LOG_FILE"
echo " "                                                     | tee -a 	"$LOG_FILE"
echo " "                                                     | tee -a 	"$LOG_FILE"
source /srv/homeassistant/bin/activate                       | tee -a 	"$LOG_FILE"
pip3 install --upgrade homeassistant                         | tee -a 	"$LOG_FILE"

systemctl restart home-assistant@homeassistant.service       | tee -a 	"$LOG_FILE"





exit 1
