#!/bin/bash
## Bash Script to clear cached memory on (Ubuntu/Debian) Linux
##	sudo sh /home/pi/programs/command/HAupdate.sh
### BEGIN INIT INFO
# Provides:          update_hass.sh
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: update_hass.sh
### END INIT INFO

mkdir -p /home/pi/log/install
LOG_FILE="/home/pi/log/HAupdate.log"


echo "Stopping Home Assistant Service"                          | tee -a 	"$LOG_FILE"
sudo systemctl stop home-assistant@homeassistant.service        | tee -a 	"$LOG_FILE"

rm -f /home/homeassistant/.homeassistant/home-assistant.log     | tee -a 	"$LOG_FILE"
rm -f /home/homeassistant/.homeassistant/home-assistant_v2.db   | tee -a 	"$LOG_FILE"
sleep 2

echo "Changing to the homeassistant user"                       | tee -a 	"$LOG_FILE"
sudo -u homeassistant -H /bin/bash << EOF                       | tee -a 	"$LOG_FILE"

echo "Changing to Home Assistant venv"                          | tee -a 	"$LOG_FILE"
source /srv/homeassistant/bin/activate                          | tee -a 	"$LOG_FILE"

echo " Update to latest version of Home Assistant"              | tee -a 	"$LOG_FILE"
pip3 install --upgrade homeassistant                            | tee -a 	"$LOG_FILE"

echo "Deactivating virtualenv"                                  | tee -a 	"$LOG_FILE"
deactivate                                                      | tee -a 	"$LOG_FILE"
EOF                                                             | tee -a 	"$LOG_FILE"

echo "Changing to the pi user"                                  | tee -a 	"$LOG_FILE"
sudo -u pi -H /bin/bash << EOF                                  | tee -a 	"$LOG_FILE"

echo "Starting Home Assistant Service"                          | tee -a 	"$LOG_FILE"
sudo systemctl start home-assistant@homeassistant.service       | tee -a 	"$LOG_FILE"





exit 1
